export const GET_LIST = 'HOME/GET_LIST';

export const UPDATE_TYPE = 'HOME/UPDATE_TYPE';

export const UPDATE_LOVE = 'HOME/UPDATE_LOVE';

export const UPDATE_PAGE = 'HOME/UPDATE_PAGE';

export const UPDATE_SEARCH_TEXT = 'HOME/UPDATE_SEARCH_TEXT';

export const UPDATE_NEXT_PAGE_TOKEN = 'HOME/UPDATE_NEXT_PAGE_TOKEN';